FROM ubuntu:bionic
LABEL maintainer "hirokiyokoyama <h-yokoyama@craft-server.co.jp>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gnupg \
    && rm -rf /var/lib/apt/lists/*
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 421C365BD9FF1F717815A3895523BAEEB01FA116

RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list

RUN apt-get update && apt-get install \
    -o Dpkg::Options::="--force-confnew" --no-install-recommends -y \
    python-rosdep \
    python-rosinstall \
    python-vcstools \
    ros-melodic-ros-base \
    build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && rosdep init

# to resolve *.local hostname
RUN apt-get update && apt-get install --no-install-recommends -y \
    avahi-daemon \
    libnss-mdns \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/#enable-dbus=yes/enable-dbus=no/g' /etc/avahi/avahi-daemon.conf

# setup catkin_ws
RUN mkdir -p /catkin_ws/src && cd /catkin_ws/src \
    && . /opt/ros/melodic/setup.sh && catkin_init_workspace \
    && cd .. && catkin_make

RUN cd /catkin_ws/src && git clone https://github.com/intel-ros/realsense.git \
    && cd realsense && git checkout 2.0.3 \
    # to remove dependency on librealsense2
    && git checkout 44413ec -- realsense2_camera/package.xml \
    && git checkout 8ab6973 -- realsense2_camera/CMakeLists.txt
RUN apt-get update && apt-get install -y \
    unzip wget git software-properties-common udev \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/jetsonhacks/buildLibrealsense2TX.git \
    && cd buildLibrealsense2TX && sed -i -e 's/sudo//g' ./installLibrealsense.sh

# GLFW3 seems to depend on GLU
RUN apt-get update && apt-get install -y \
    libglu1-mesa-dev \
    && rm -rf /var/lib/apt/lists/*

RUN echo "Please run: nvidia-docker run THIS_IMAGE && docker commit CONTAINER realsense-jetson-tmp"
WORKDIR /buildLibrealsense2TX
ENV CUDACXX /usr/local/cuda/bin/nvcc
CMD ./installLibrealsense.sh

